name: sample-pipeline
version: "0.1"
description: Example pipeline wiring planner -> implementor -> reviewer

directories:
  main:
    alias: main
    kind: path
    path: .
  scratch:
    alias: scratch
    kind: temp
    base: /tmp/codex-swarm
  worktree:
    alias: worktree
    kind: worktree
    source: .
    ref: HEAD

agent_types:
  summarizer:
    alias: summarizer
    prePrompt: |
      You summarize the content passed to you and highlight risks.
    access: read-only
    command: codex
    args:
      - chat

stages:
  - alias: planning
    agents:
      - alias: planner-1
        type: planner
        input: stdin
        root: main
        directories: [main]
  - alias: implementation
    agents:
      - alias: implementor-1
        type: implementor
        input: planner-1
        root: worktree
        directories: [worktree, scratch]
      - alias: reviewer-1
        type: reviewer
        input: implementor-1
        root: worktree
        directories: [worktree]
      - alias: summary
        type: summarizer
        input: reviewer-1
        root: main
        directories: [main]
